name = "admin" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true

[[routes]]
pattern = "admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "graph.instagram.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "quiz.int.vidio.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "live.iflix.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "blog.webex.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "investors.spotify.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "cache.netflix.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "zaintest.vuclip.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "ads.ruangguru.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "io.ruangguru.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "api.midtrans.com.admin.ari-andika2.site"
custom_domain = true

[[routes]]
pattern = "investor.fb.com.admin.ari-andika2.site"
custom_domain = true
