name = "cf" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
[[routes]]
pattern = "free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.free-cf.xhamster.biz.id"
custom_domain = true
[[routes]]
pattern = "free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.free-cf.turah.my.id"
custom_domain = true
[[routes]]
pattern = "free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.free-cf.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.free-cf.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.free-cf.kere.us.kg"
custom_domain = true
[[routes]]
pattern = "free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.free-cf.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.free-cf.najah.biz.id"
custom_domain = true
[[routes]]
pattern = "sublink.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "inputbugwildcard.cloudproxyip.my.id.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "inputbugwildcard.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "web.bmkg.xyz"
custom_domain = true

[[routes]]
pattern = "ava.game.naver.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "subapi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "bugskti.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "bugskti.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "subapi.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.loss.zifxoyfpuf0uf0ycphcoyf0684wd.us.kg"
custom_domain = true
