name = "cf" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "kang.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.merapi.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.wong.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.wong.ndeso.web.id"
custom_domain = true
