name: Update Proxy IP

on:
  schedule:
    - cron: '0 17 * * 0'  # Setiap hari pukul 00:00 WIB (17:00 UTC)
  workflow_dispatch:  # Memungkinkan untuk menjalankan manual melalui GitHub UI

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update proxy ip
      env:
        IP_FILE: 'proxyip.txt'  # File proxy yang akan diperiksa
        API_URL: 'https://p01--boiling-frame--kw6dd7bjv2nr.code.run/check?ip={ip}&host=speed.cloudflare.com&port={port}&tls=true'
      run: |
        python update_proxy.py

    - name: Ensure update_proxyip.txt exists
      run: |
        if [ -f "update_proxyip.txt" ]; then
          echo "File update_proxyip.txt exists."
        else
          echo "File update_proxyip.txt not found!"
          exit 1  # Menghentikan proses jika file tidak ditemukan
        fi

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add update_proxyip.txt
        git add error.txt
        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          git commit -m "Update proxy IP status"
          git push
        fi
